<a href="https://colab.research.google.com/github/vonlanot/us-food-imports/blob/main/US_Food_Imports.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# ------------------------------------------------------------------------------
# 1. Mount Google Drive to access your CSV files
# ------------------------------------------------------------------------------
from google.colab import drive
drive.mount('/content/drive')

# ------------------------------------------------------------------------------
# 2. Import necessary libraries
# ------------------------------------------------------------------------------
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options for pandas (optional, but good for viewing dataframes)
pd.set_option('display.max_columns', None) # Display all columns
pd.set_option('display.max_rows', 100)     # Display up to 100 rows
pd.set_option('display.width', 1000)      # Adjust display width

# ------------------------------------------------------------------------------
# 3. Define the base path to data
# ------------------------------------------------------------------------------
base_path = '/content/drive/My Drive/Colab Notebooks/My Data/US_Food_Imports/'

# ------------------------------------------------------------------------------
# 4. Load each cleaned CSV into a separate Pandas DataFrame with 'latin1' encoding
# ------------------------------------------------------------------------------

# Monetary Value Data
df_monetary_value = pd.read_csv(base_path + 'us_food_imports_monetary.csv', encoding='latin1')

# Quantity Data
df_quantity = pd.read_csv(base_path + 'us_food_imports_quantity.csv', encoding='latin1')

# Price Rate Data
df_price_rate = pd.read_csv(base_path + 'us_food_imports_price_rate.csv', encoding='latin1')

# Percentage Data
df_percentage = pd.read_csv(base_path + 'us_food_imports_percentage.csv', encoding='latin1')

# ------------------------------------------------------------------------------
# 5. Display the first few rows and info for each DataFrame to confirm loading
# ------------------------------------------------------------------------------
print("--- df_monetary_value ---")
print(df_monetary_value.head())
print(df_monetary_value.info())

print("\n--- df_quantity ---")
print(df_quantity.head())
print(df_quantity.info())

print("\n--- df_price_rate ---")
print(df_price_rate.head())
print(df_price_rate.info())

print("\n--- df_percentage ---")
print(df_percentage.head())
print(df_percentage.info())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
--- df_monetary_value ---
              Commodity        Country        UOM Category SubCategory  YearNum  FoodValue
0    Total live animals         CANADA  Million $  Animals       Foods     1999      876.9
1    Total live animals         MEXICO  Million $  Animals       Foods     1999      292.2
2    Total live animals  REST OF WORLD  Million $  Animals       Foods     1999        0.1
3  Bovine animals, live         CANADA  Million $  Animals       Foods     1999      639.0
4  Bovine animals, live         MEXICO  Million $  Animals       Foods     1999      292.1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13780 entries, 0 to 13779
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Commodity    13780 non-null  object
 1   Country      13780 non-null  object
 2   UOM          13780 non-null  object
 3   Category     13780 non-null  object
 4   SubCategory  13780 non-null  object
 5   YearNum      13780 non-null  int64
 6   FoodValue    13780 non-null  float64
dtypes: float64(1), int64(1), object(5)
memory usage: 753.7+ KB
None

--- df_quantity ---
               Commodity           Country    UOM Category SubCategory  YearNum  FoodValue
0     Total live animals  WORLD (Quantity)  1,000  Animals       Foods     1999     6058.4
1   Bovine animals, live  WORLD (Quantity)  1,000  Animals       Foods     1999     1868.8
2            Swine, live  WORLD (Quantity)  1,000  Animals       Foods     1999     4136.3
3  Sheep and goats, live  WORLD (Quantity)  1,000  Animals       Foods     1999       53.2
4           Live poultry  WORLD (Quantity)  1,000  Animals       Foods     1999     8113.5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2210 entries, 0 to 2209
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Commodity    2210 non-null   object
 1   Country      2210 non-null   object
 2   UOM          2210 non-null   object
 3   Category     2210 non-null   object
 4   SubCategory  2210 non-null   object
 5   YearNum      2210 non-null   int64
 6   FoodValue    2210 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 121.0+ KB
None

--- df_price_rate ---
            Commodity Country             UOM Category           SubCategory  YearNum    FoodValue
0               Meats   WORLD  Dollars per mt   Prices  Imported food prices     1999  2264.865240
1  Fish and shellfish   WORLD  Dollars per mt   Prices  Imported food prices     1999  5280.605555
2               Dairy   WORLD  Dollars per mt   Prices  Imported food prices     1999  3113.453815
3          Vegetables   WORLD  Dollars per mt   Prices  Imported food prices     1999   758.737529
4              Fruits   WORLD  Dollars per mt   Prices  Imported food prices     1999   611.808099
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Commodity    312 non-null    object
 1   Country      312 non-null    object
 2   UOM          312 non-null    object
 3   Category     312 non-null    object
 4   SubCategory  312 non-null    object
 5   YearNum      312 non-null    int64
 6   FoodValue    312 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 17.2+ KB
None

--- df_percentage ---
                 Commodity Country      UOM      Category     SubCategory  YearNum  FoodValue
0                  Animals   WORLD  percent  Food dollars  Subtotal foods     2000  12.699873
1                Beverages   WORLD  percent  Food dollars           Foods     2000   8.198215
2                Beverages   WORLD  percent  Food dollars  Subtotal foods     2000   8.198215
3      Cocoa and chocolate   WORLD  percent  Food dollars           Foods     2000  -7.750411
4  Coffee, tea, and spices   WORLD  percent  Food dollars           Foods     2000  -4.492605
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Commodity    1125 non-null   object
 1   Country      1125 non-null   object
 2   UOM          1125 non-null   object
 3   Category     1125 non-null   object
 4   SubCategory  1125 non-null   object
 5   YearNum      1125 non-null   int64
 6   FoodValue    1125 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 61.7+ KB
None